apiVersion: v2
name: hw4-chart
description: A Helm chart for hw4
type: application
version: 0.1.0
appVersion: 1.0.1

dependencies:
  - name: postgresql
    version: 15.x.x
    repository: https://charts.bitnami.com/bitnami
    tags:
      - hw4-database1
