{
 "title": "HW5 dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Latency с разбивкой по API и квантилями по 0.5",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le,pod, uri) (rate(http_server_requests_seconds_bucket{uri=\"/api/v1/user/{id}\"}[1m]))) * 1000\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency с разбивкой по API и квантилями по 0.95",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le,pod, uri) (rate(http_server_requests_seconds_bucket{uri=\"/api/v1/user/{id}\"}[1m]))) * 1000\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency с разбивкой по API и квантилями по 0.99",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le,pod, uri) (rate(http_server_requests_seconds_bucket{uri=\"/api/v1/user/{id}\"}[1m]))) * 1000\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency с разбивкой по API и квантилями по 1",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by(le,pod, uri) (rate(http_server_requests_seconds_bucket{uri=\"/api/v1/user/{id}\"}[1m]))) * 1000\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency в целом по сервису и квантилями по 0.5",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency в целом по сервису и квантилями по 0.95",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency в целом по сервису и квантилями по 0.99",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency в целом по сервису и квантилями по 1",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS с разбивкой по API",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (pod, uri) (rate(http_server_requests_seconds_count{uri=\"/api/v1/user/{id}\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS в целом по сервису",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "targets": [
    {
     "expr": "sum (rate(nginx_ingress_controller_requests[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate с разбивкой по API",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by (pod, uri) (rate(http_server_requests_seconds_count{status=~\"4..\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate в целом по сервису",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 10 },
   "targets": [
    {
     "expr": "sum (rate(nginx_ingress_controller_requests{status=~\"4..\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}