apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hw6-ingress-app
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "http://hw6-app-hw6-chart.hw6.svc.cluster.local/api/v1/auth"
    nginx.ingress.kubernetes.io/auth-signin: "http://$host/api/v1/login"
    nginx.ingress.kubernetes.io/auth-response-headers: "X-User-Id,X-User-Login"
spec:
  rules:
    - host: {{.Values.ingress.host}}
      http:
        paths:
          - path: /api/v1/profile
            pathType: Prefix
            backend:
              service:
                name: {{ include "hw6-chart.fullname" . }}
                port:
                  number: 80
