apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hw6-ingress-auth
spec:
  rules:
  - host: {{.Values.ingress.host}}
    http:
      paths:
        - path: /api/v1/login
          pathType: Prefix
          backend:
            service:
              name: {{ include "hw6-chart.fullname" . }}
              port:
                number: 80
        - path: /api/v1/logout
          pathType: Prefix
          backend:
            service:
              name: {{ include "hw6-chart.fullname" . }}
              port:
                number: 80
        - path: /api/v1/register
          pathType: Prefix
          backend:
            service:
              name: {{ include "hw6-chart.fullname" . }}
              port:
                number: 80
        - path: /api/v1/auth
          pathType: Prefix
          backend:
            service:
              name: {{ include "hw6-chart.fullname" . }}
              port:
                number: 80