replicaCount: 3

image:
  repository: sden81/otus-ms-arch-2023-12-hw5-img
  tag: v1.1

service:
  type: ClusterIP
  port: 8081

postgresql:
  enabled: true
  auth:
    existingSecret: hw4-app-secret-env
    postgresqlUsername: postgres
    postgresqlPassword: passwd
    postgresqlDatabase: postgres
    postgresqlSchema: hw5
  service:
    port: "5432"

ingress:
  enabled: true
  host: arch.homework

autoscaling:
  enabled: false

serviceAccount:
  create: false

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
  releaseName: stack

metrics:
  serviceMonitor:
    enabled: true